[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Запускает все UI автотесты
    smoke: Запускает все smoke автотесты
    regression: Запускает все regression автотесты
    registartion: Запускает все registartion автотесты
    authorization: Запускает все authorization
