[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Запускает все UI автотесты
    smoke: Запускает все smoke автотесты
    regression: Запускает все regression автотесты
    registration: Запускает все registration автотесты
    authorization: Запускает все authorization
    courses: для тестов, связанных с курсами
 